# Q3 Using Scikit-Learn

In [139]:
import numpy as np
import pandas as pd
import time
import gc
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer


In [140]:
# Change to your GA Tech ID
ga_id = 'zzheng309'
# Requires a print() statement do not modify below print statement
print(ga_id)

zzheng309


# Q3.1 Data Import and Cleansing Setup

In [141]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set. We've started this for you. 
# XXX

# -------------------------------
# ADD CODE HERE
data = pd.read_csv('pulsar_stars.csv')
# -------------------------------

# XXX
# TODO: Separate out the x_data and y_data. We've started this for you.
# XXX

# -------------------------------
# ADD CODE HERE
x_data = data.iloc[:,:-1]
y_data = data.iloc[:,-1]
# -------------------------------


In [142]:
# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' 
# set to 614.
# 

# -------------------------------
# ADD CODE HERE
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, shuffle=True, random_state=614)
# -------------------------------

# Q3.2 Linear Regression 

In [143]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE
# 
reg = LinearRegression()
reg.fit(x_train, y_train)
# -------------------------------

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [144]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
y_train_pred = reg.predict(x_train)
number_filter = y_train_pred >= 0.5
y_train_pred_rounded = np.zeros(len(y_train_pred))
y_train_pred_rounded[number_filter] = 1.0
print(accuracy_score(y_train_pred_rounded, y_train))

# -------------------------------

0.9720625798212005


In [145]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
y_test_pred = reg.predict(x_test)
number_filter = y_test_pred >= 0.5
y_test_pred_rounded = np.zeros(len(y_test_pred))
y_test_pred_rounded[number_filter] = 1.0
print(accuracy_score(y_test_pred_rounded, y_test))
# -------------------------------

0.9696461824953445


# Q3.3 Random Forest Classifier

In [146]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# Set 'random_state' to 614
# XXX

# -------------------------------
# ADD CODE HERE

rf = RandomForestClassifier(random_state=614)
rf.fit(x_train, y_train)
# -------------------------------

/Users/Andrew/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=614, verbose=0, warm_start=False)

In [147]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
y_train_pred = rf.predict(x_train)
print(accuracy_score(y_train_pred, y_train))
# -------------------------------

0.9968071519795658


In [148]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
y_test_pred = rf.predict(x_test)
print(accuracy_score(y_test_pred, y_test))
# -------------------------------

0.9767225325884544


## Q3.3.1 Feature Importance

In [149]:
# XXX
# TODO: Determine the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
importances = rf.feature_importances_
print(importances)
# -------------------------------

[0.36631348 0.05096543 0.25857456 0.11768744 0.05862141 0.03806286
 0.05627799 0.05349682]


In [150]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

sorted_index = np.argsort(importances)[::-1]
print(sorted_index)
# -------------------------------

[0 2 3 4 6 7 1 5]


## Q3.3.2 Hyper-parameter Tuning

In [136]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# 'n_estimators': [4, 16, 256]
# 'max_depth': [2, 8, 16]
# XXX

# -------------------------------
# ADD CODE HERE
n_estimators = [4, 16, 256]
max_depth = [2, 8, 16]

random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth}

rf_random = GridSearchCV(estimator = rf,
            param_grid = random_grid, 
            cv = 5)

rf_random.fit(x_train,y_train)
# -------------------------------

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=614, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [4, 16, 256], 'max_depth': [2, 8, 16]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [137]:
# XXX
# TODO: Get the best params, using .best_params_
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(rf_random.best_params_)
# -------------------------------

{'max_depth': 16, 'n_estimators': 256}


In [138]:
# XXX
# TODO: Get the best score, using .best_score_.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

print(rf_random.best_score_)

# -------------------------------

0.9794859514687101


# Q3.4 Support Vector Machine

## Q3.4.1 Pre-process

In [153]:
# XXX
# TODO: Pre-process the data to standardize it, otherwise the grid search will take much longer.
# XXX

# -------------------------------
# ADD CODE HERE

scaler = StandardScaler()
scaler.fit(x_train)
x_train_std = scaler.transform(x_train)
# -------------------------------

## Q3.4.2 Classification

In [173]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
# ADD CODE HERE

svm = SVC()
svm.fit(x_train_std, y_train)
# -------------------------------

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [174]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
y_train_pred = svm.predict(x_train_std)
print(accuracy_score(y_train_pred, y_train))
# -------------------------------

0.9802043422733078


In [175]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

x_test_std = scaler.transform(x_test)
y_test_pred = svm.predict(x_test_std)
print(accuracy_score(y_test_pred, y_test))
# -------------------------------

0.9757914338919925


## Q3.4.3 Hyper-parameter Tuning

In [180]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# 'kernel':('linear', 'rbf') 
# 'C':[0.01, 0.1, 1.0]
# XXX

# -------------------------------
# ADD CODE HERE

parameters = {'kernel':('linear', 'rbf'), 'C':[0.01,0.1,1.0]}
svm1=SVC(gamma='auto')
clf1 = GridSearchCV(svm1, parameters, cv=10,n_jobs=-1, return_train_score=True)
clf1.fit(x_train_std, y_train)

# -------------------------------

GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'kernel': ('linear', 'rbf'), 'C': [0.01, 0.1, 1.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [181]:
# XXX
# TODO: Get the best score, using .best_score_.
# Note: Set n_jobs=-1 and return_train_score=True
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
# -------------------------------
print(clf1.best_score_)

0.9794859514687101


In [182]:
# XXX
# TODO: Calculate the training and test set accuracy values after hyperparameter tuning and standardization. 
# XXX

# -------------------------------
# ADD CODE HERE
y_train_pred = clf1.predict(x_train_std)
train_accuracy = accuracy_score(y_train, y_train_pred)
y_test_pred = clf1.predict(x_test_std)
test_accuracy = accuracy_score(y_test, y_test_pred)
# -------------------------------

In [183]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(train_accuracy)
# -------------------------------

0.9797254150702427


In [184]:
# XXX
# TODO: Test its accuracy (on the test set) using the accuracy_score method.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(test_accuracy)
# -------------------------------

0.9778398510242086


## Q3.4.4 Cross Validation Results 

In [185]:
# XXX
# TODO: Get the rank test score for all hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement

print(clf1.cv_results_['rank_test_score']) 

# -------------------------------

[5 6 3 4 1 2]


In [186]:
# XXX
# TODO: Get the mean testing score for all of hyperparameter values that you obtained in Q3.4.3. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX
# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(clf1.cv_results_['mean_test_score'])
# -------------------------------

[0.97637292 0.97070562 0.97900702 0.97812899 0.97948595 0.97916667]


# Q3.5 PCA

In [191]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# NOTE: Use the full x data set for this section 'x_data'

# -------------------------------
# ADD CODE HERE
# You should see an output here of PCA(copy=True....)
pca = PCA(n_components=8, svd_solver='full')
pca.fit(x_data)
# -------------------------------

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
  svd_solver='full', tol=0.0, whiten=False)

In [193]:
# XXX
# TODO: Get percentage of variance explained by each of the selected components
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(pca.explained_variance_ratio_)
# -------------------------------

[8.71053041e-01 7.81934383e-02 4.11562290e-02 6.15967691e-03
 2.43717952e-03 9.58578490e-04 3.90570992e-05 2.79968662e-06]


In [194]:
# XXX
# TODO: Get the singular values corresponding to each of the selected components.
# XXX

# -------------------------------
# ADD CODE HERE
# Requires a print() statement
print(pca.singular_values_)
# -------------------------------

[14430.28004546  4323.5214088   3136.68022725  1213.47665361
   763.30168073   478.70316467    96.62788002    25.87063984]
